language: scala
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
script:
- sbt +test +package
after_success:
- "./travis-publish.sh"
env:
  global:
  - secure: VXYQcFZR6ncZ5GGwS4wRo43r3IKiJPO+VVKhDpWZ/qJ0+jadYQfUXz+VhXqwlxE5BBqWePwwgfZxUNM0ImH7Qk9eYBOqo5S6k4kQpFFEHwZ7LFVY4/CYoGLzF9AvLjJVXgnAORLyFzmE33EVQbIs9WU2uxHQP6LJRde/OYdHDbtDw2miBy+xFwiibZ2v5dhiwWF7nQmXyxxPw8umtq5t3zYZoI1RFGW6xWKX/h1JlgrYJtmH/QPxoTjYA7HYZk3t0VXd4CYMZVReR+0nwAYrL+86RBQWd+OiA0mCYLOmZ8UAo3R5vdr7I2JDQp4A/izscxZ4R20JEd4OJs0RfpSK5vUiKiCcbDvwbQAxYsI4HOUPhRGO2xqPsO18R80NVVhx2BuZ0Ucpz5XdKhUtJ/fHueYyyRERvHoPz4pzU78xjO1wrkYQJy7kbqtFBTYbnWt1vuBMmxjVsqUlI7ldu7oNaPGK82RLB28WlmgEP5ZN+RUjgxqnEUpaSQq8yotCtK+E8UkU9QN7vukNYPOnOcBbWQP+lsTgmKjwEN0IGCjM7/ghdJkI1ymGL40GwHv0hiQgWOo2iwvvvMc6m2mo8qNvk6SqgyfKU5+2OCk4lGr63kERxjrX2FY78zHcY6jL49iYSOsyROE8ZFDyae6sFLjOF6ZaR9ubCQbGIAOyM0yPPNg=
  - secure: YKsUvi4bBDJHELqyrEk+WK6Wj3Gp29tIUlTG5J2utyEqJSKDwU5EjnoQvBcFyWpZKnWiEKvxZr2aKiJyNaOpjraRQHCW3lTmBsmIUgy7AcukTEJkQeO47W4H7XAlxM4pbgVaHo0ReOVqPmuj6V6JrHQOLqz4KtOuenEzuhKqqpJWn+2gIJwW9HN3glSJqT8glmrrGoISIqX2fbA/lc908rqorjbH4if+Bc7/+MR0cCGtCFdAuIqQCq3qxBFlvNIJiAkpgIYXFnDLaFONJf/03YF/LsrSjFR1hr37R5ZQvdXqd3iTjfOruly8bakMDWtv9GVZVs3gLaMCG0wxTEzc5UMRqrA4RIyoXVfl5UrNQ97ZobN3CD8vpFFsy8tdcAJopVjPkIJ8J6O1eZ8pPlVsbOHyC+CZoDk+oU3v/jCGsudnYGYE3m9Ek6W+2KGBkDkOhBjkEJ7In6JY+IOSvIUd+y4vfYowDzGTz7B2a6M0ZZ8Qwv+Pm0MihTboLH3fz8yWFmaq2TnXc2atxWa8gSPvDwOQV5FrEjfTejGF2lkNTpfHx7Stp4GqFstG2ppkRZMg5wKHA4FifmLTECOdfHFWX5+Ikj4gsC7nuD8vwG7UbarDykXF9l2dB15fp2i9c3yw2L5hjXVuuLbbJJ+VLrH7Bk6vgSttJtKrAyhPuJbwhvE=
